#!/bin/bash

set -e
cd *

mkdir build
cd build

mkdir -p "$INSTALL_PATH/tools/$TARGET/bin"

../configure \
	--prefix="$INSTALL_PATH/tools" \
	--target="$TARGET" \
	--with-sysroot="$SYSROOT" \
	--disable-werror \
	--disable-nls \
	--enable-64-bit-bfd \
	--enable-gprofng=no

make -j${JOBS}
make install -j1
