#!/bin/bash

set -e
cd *

# TODO use `sources` in `package.json`
./contrib/download_prerequisites

mkdir build
cd build

../configure \
	--prefix="$SYSROOT/tools" \
	--target="$TARGET" \
	--with-sysroot="$SYSROOT" \
	--with-newlib \
	--without-headers \
	--enable-languages=c,c++ \
	--disable-hosted-libstdcxx \
	--disable-libatomic \
	--disable-libgomp \
	--disable-libquadmath \
	--disable-libsanitizer \
	--disable-libssp \
	--disable-multilib \
	--disable-nls \
	--disable-shared \
	--disable-threads \
	--disable-vtv

mkdir -p "$SYSROOT/usr/include"

make -j$JOBS all-gcc
make install-gcc
make -j$JOBS all-target-libgcc
make install-target-libgcc
