#!/bin/bash

set -e
cd *

mkdir build
cd build

../configure \
	--prefix="/usr" \
	--target="$TARGET" \
	--with-sysroot="$SYSROOT" \
	--without-headers \
	--without-newlib \
	--enable-languages=c,c++ \
	--disable-shared \
	--disable-hosted-libstdcxx \
	--disable-wchar_t \
	--disable-libssp \
	--disable-libsanitizer \
	--disable-libquadmath

make -j$JOBS all-gcc
make install-gcc
make -j$JOBS all-target-libgcc
make install-target-libgcc
make -j$JOBS all-target-libstdc++-v3
make install-target-libstdc++-v3
