#!/bin/bash

set -e
cd *

mkdir build
cd build

../libstdc++-v3/configure   \
    --host="$TARGET"        \
    --build="$BUILD"        \
    --prefix="/usr"         \
    --disable-multilib      \
    --disable-nls           \
    --disable-libstdcxx-pch \
    --with-gxx-include-dir="/tools/$TARGET/include/c++/15.1.0"

make
make DESTDIR=$SYSROOT install
rm -v $SYSROOT/usr/lib/lib{stdc++,stdc++fs,supc++}.la