#!/bin/bash

set -e
cd *

mkdir build
cd build

../libstdc++-v3/configure   \
    --host="$HOST"          \
    --build="$BUILD"        \
    --prefix="/usr"         \
    --disable-multilib      \
    --disable-nls           \
    --disable-libstdcxx-pch \
    --with-gxx-include-dir="/tools/$HOST/include/c++/$PKG_VERSION"

make
make DESTDIR=$SYSROOT install
rm -fv $SYSROOT/usr/lib/lib{stdc++,stdc++fs,supc++}.la