#!/bin/bash

set -e
cd *

./configure \
	--build="$BUILD" \
	--host="$HOST" \
	--target="$HOST" \
	--prefix="/usr" \
	--enable-optimize \
	--enable-shared

make -j${JOBS}
make DESTDIR=$INSTALL_PATH install
