[package]
name = "blimp-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
serde = { version = "1.0.219", features = ["derive"] }

[features]
default = []
network = ["common/network"]
