#!/bin/bash

set -e
cd *

# TODO use `sources` in `package.json`
./contrib/download_prerequisites

mkdir build
cd build

../configure \
	--prefix="/usr" \
	--target="$TARGET" \
	--with-sysroot="$SYSROOT" \
	--enable-languages=c,c++ \
	--enable-initfini-array \
	--enable-libstdcxx-filesystem-ts

mkdir -p "$SYSROOT/usr/include"

make -j$JOBS all-gcc
make install-gcc
make -j$JOBS all-target-libgcc
make install-target-libgcc
make -j$JOBS all-target-libstdc++-v3
make install-target-libstdc++-v3
