#!/bin/bash

set -e
cd *

# TODO use `sources` in `package.json`
./contrib/download_prerequisites

# Patch
case ${HOST%%-*} in
	x86_64)
		sed -e '/m64=/s/lib64/lib/' -i.orig gcc/config/i386/t-linux64
	;;
esac
sed '/thread_header =/s/@.*@/gthr-posix.h/' -i libgcc/Makefile.in libstdc++-v3/include/Makefile.in

mkdir build
cd build

../configure \
	--prefix="/usr"                 \
	--build="$BUILD"                \
	--host="$HOST"                  \
	--target="$TARGET"              \
	--with-build-sysroot="$SYSROOT" \
	--disable-nls                   \
	--disable-multilib              \
	--disable-libatomic             \
	--disable-libgomp               \
	--disable-libquadmath           \
	--disable-libssp                \
	--disable-libvtv                \
	--enable-default-pie            \
	--enable-default-ssp            \
	--enable-languages=c,c++

make -j$JOBS all-gcc
make DESTDIR="$SYSROOT" install-gcc
make -j$JOBS all-target-libgcc
make DESTDIR="$SYSROOT" install-target-libgcc
make -j$JOBS all-target-libstdc++-v3
make DESTDIR="$SYSROOT" install-target-libstdc++-v3

ln -fsv gcc "$SYSROOT/usr/bin/cc"