#!/bin/bash

set -e
cd *

mkdir build
cd build

../configure            \
	--prefix="/usr"     \
	--build="$BUILD"    \
	--host="$TARGET"    \
	--disable-nls       \
	--enable-shared     \
	--enable-gprofng=no \
	--disable-werror    \
	--enable-64-bit-bfd

make -j${JOBS}
make DESTDIR="$INSTALL_PATH" install -j1
rm -v "$INSTALL_PATH/usr/lib/lib"{bfd,ctf,ctf-nobfd,opcodes}.{a,la}
