name: Check
on: [push, pull_request]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: cargo fmt --check
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build (offline-mode)
        run: cargo build
      - name: Build (online-mode)
        run: cargo build --features network
      - name: Clippy (offline-mode)
        run: cargo clippy --all-targets -- -D warnings
      - name: Clippy (online-mode)
        run: cargo clippy --features network --all-targets -- -D warnings
      - name: Unit tests (offline-mode)
        run: cargo test
      - name: Unit tests (online-mode)
        run: cargo test --features network --all-targets
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build (offline-mode)
        run: cargo build --release
      - name: Build (online-mode)
        run: cargo build --release --features network
      - name: Build documentation
        run: cargo doc --all-features --no-deps
